#!/bin/env bash
# Installs Nginx Web Server with conditions

# Update package list
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Adjust the firewall
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx (without using systemctl)
sudo service nginx restart
