#!/bin/env bash
# Installs Nginx Web Server with conditions

# Update package list
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a simple HTML page with "Hello World!"
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart Nginx (without using systemctl)
sudo service nginx restart
