#!/usr/bin/env bash
# Installs Nginx Web Server with conditions
# and redirects server permanently

# Update package list
sudo apt update

# Install Nginx
sudo apt install -y nginx

# replace default text in index.html with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# redirect server(/redirect me) to another page permanently
string_to_find='server_name _;'
string_to_append='\\n\tlocation /redirect_me {\n\treturn 301 http://google.com;\n\t}'
if ! grep -q "$string_to_append" /etc/nginx/sites-available/default; then
	sed -i "/$string_to_find/a$string_to_append" /etc/nginx/sites-available/default
fi

# Restart Nginx (without using systemctl)
sudo service nginx restart
