#!/usr/bin/env bash
# Install and configure HAproxy on load balancing server
# Configure HAproxy so that it send traffic to the 2 web servers
# Distribute requests using a roundrobin algorithm

# Update package list
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

path_to_file="/etc/haproxy/haproxy.cfg"
# remove all commented lines
# sed -i "/^\W*#.*/" /etc/nginx/sites-available/default

# edit the HAProxy configuration file to include the
# frontend and backend configurations
string_to_append="backend devshowcase.tech-backend
        balance roundrobin
        server 209149-web-01 100.25.21.246:80 check
        server 209149-web-02 3.85.41.202:80 check

frontend http
        bind *:80
        mode http
        default_backend devshowcase.tech-backend"

if ! grep -q "$string_to_append" "$path_to_file"; then
	echo "\\$string_to_append" | sudo tee -a /etc/haproxy/haproxy.cfg
fi

# Make sure that HAproxy can be managed via an init script
# shellcheck disable=SC2154
# echo "$haproxy_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi

# Make sure that HAproxy can be managed via an init script
# sudo systemctl enable haproxy

# Restart Nginx (without using systemctl)
# sudo haproxy restart
