#!/usr/bin/env bash
# Install and configure HAproxy on load balancing server
# Configure HAproxy so that it send traffic to the 2 web servers
# Distribute requests using a roundrobin algorithm

# Update package list
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Adjust the firewall, enabling the most restrictive profile configured
sudo ufw allow 'Nginx HTTP'

path_to_file="/etc/haproxy/haproxy.cfg"
# remove all commented lines
# sed -i "/^\W*#.*/" /etc/nginx/sites-available/default

# edit the HAProxy configuration file to include the
# frontend and backend configurations
string_to_append="backend devshowcase.tech-backend
        balance roundrobin
        server 209149-web-01 100.25.21.246:80 check
        server 209149-web-02 3.85.41.202:80 check

frontend http
        bind *:80
        mode http
        default_backend devshowcase.tech-backend"

if ! grep -q "$string_to_append" "$path_to_file"; then
	echo "\\$string_to_append" | sudo tee -a /etc/haproxy/haproxy.cfg
fi

# Make sure that HAproxy can be managed via an init script
#!/usr/bin/env bash
 # Install and configure HAproxy on your lb-01 server.

 echo -e "Installing and Configuring HAProxy on server....\n"

 function install() {
         command -v "$1" &> /dev/null

         # disabling shellcheck=SC2181
         if [ $? -ne 0 ]; then
                 echo -e "Installing: $1\n"
                 sudo apt-get update -y -qq && sudo apt-get install -y "$1" -qq
                 echo -e "\n"
         else
                 echo -e "${1} is already installed in server.\n"
         fi
 }

 # Install HAProxy
 install haproxy

 echo -e "configuring........\n"

 # backup default server config file
 sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

 haproxy_config="
         defaults
           mode http
           timeout client 15s
           timeout connect 10s
           timeout server 15s
           timeout http-request 10s

         frontend clickviral-tech-frontend
             bind *:80
             default_backend clickviral-tech-backend

         backend clickviral-tech-backend
             balance roundrobin
             server 430728-web-01 54.167.187.121:80 check
             server 430728-web-02 100.25.3.235:80 check
         "


 # shellcheck disable=SC2154
 # echo "$haproxy_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

 # enable haproxy to be started by init script
 echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

 if [ "$(pgrep -c haproxy)" -le 0 ]; then
         sudo service haproxy start
 else
         sudo service haproxy restart
 fi

# Make sure that HAproxy can be managed via an init script
# sudo systemctl enable haproxy
# Restart Nginx (without using systemctl)
# sudo haproxy restart
