#!/usr/bin/env bash
# what’s keeping your Ubuntu container’s Nginx installation from listening on port 8?
# Enable server blocks by creating symbolic links from these files to the sites-enabled
# If a symlink already exists, remove and recreate
# Restart nginx

# rm /etc/nginx/sites-enabled/default
# ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# service nginx restart

# Create a new Nginx configuration file
cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80;
    listen [::]:80;

    server_name _;

    location / {
        # Your website root directory
        root /var/www/html;
        index index.html index.htm;
    }
}
EOL

# Restart Nginx to apply changes
service nginx restart

