#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop.
# Displays Hi on the 9th count.

i=1
while [ $i -le 10 ]; do
	if [ $i -eq 9 ]; then
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
