#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop.
# Displays "badluck"on 4th, "goodluck" on the 8th count.

i=1
while [ $i -le 10 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
