#!/usr/bin/env bash
# displays 1 - 20 using a while loop
# using case statements prints other values at specific intervals

number=1

while [ $number -le 20 ]; do
	echo "$number"
	case $number in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	number=$((number+1))
done
