#!/usr/bin/env bash
#displays hours from 0 - 12, minutes from 1 - 59

hour=0

while [ $hour -le 12 ]; do
	minute=1
	echo "Hour: $hour"
	while [ $minute -lt 60 ]; do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
